version: '3.9' #docker-composeのバージョン
services:
  app:  #任意のサービス名
    build: 
      context: .
      dockerfile: ./infra/php/Dockerfile
    # volumes:
    #   - ./backend:/work #コンテナにマウントするディレクトリ

  web:
    build: 
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 80:80
    # volumes:
    #   - ./backend:/work
    #   - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - db
    ports:
      - 81:80
    volumes:
      - /sessions

volumes:
  db-store:
